### ISSUE TITLE
Screenshot link is invalid and doesn't show default settings

### ISSUE THREAD

**Issue by danirabbit** [keyilan/swatches#8]
Thanks for submitting your app for review in AppCenter!

screenshots should show elementary OS default settings, including window control position.

It also seems like the link in your appdata.xml is invalid. It links to [here](https://raw.githubusercontent.com/keyilan/swatches/master/screenshot.png) when it should be [here](https://raw.githubusercontent.com/keyilan/swatches/master/data/screenshot.png)

**Comment by patkaiist** [comment]
Thanks. Will fix both shortly.
